fix: Check if mExoPlayer is null
Fix NullPointerException

java.lang.NullPointerException: Attempt to invoke virtual method
'void com.google.android.exoplayer2.SimpleExoPlayer
.setPlayWhenReady(boolean)' on a null object reference