fix: Fix NullPointerException
java.lang.NullPointerException: Attempt to invoke virtual method
'long java.util.Date.getTime()' on a null object reference
at CandyPodUtils.getFormattedDateString(CandyPodUtils.java:71)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'java.net.URLConnection java.net.URL.openConnection()' on a null
object reference at CandyPodUtils.loadImage(CandyPodUtils.java:91)